### ISSUE TITLE
Simple and Impressive work, but some extreme situation may need further consideration

### ISSUE THREAD

**Issue by BoltenWang-Meta** [YBZh/EFDM#1]
Sort x and y, then match closest. To generate o copying it from y is  definately consistent with y. However, what if there is a huge margin or shift between x and y? To directly align x style with original y may not be efficient.

**Comment by YBZh** [comment]
In style transfer tasks, it is common to directly align x style with y style to achieve the required style transfer.  The only difference between our method and the traditional one is the definition of the style. Specifically, traditional methods typically adopted first and second order statistics as style knowledge, while we take a further step to consider high order statistics in an efficient manner.
