### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Lzyyaa** [YBZh/EFDM#3]
Hi, thanks for your code. 

I want to try some arbitrary style transfer, following your [README.md], I downloaded the pre-trained VGG models and the decoder pre-trained with efdm you provided.
But when I run the test.py, the error occurred: ZeroDivisionError: float division by zero.
It seems in “ymaps = int(math.ceil(float(nmaps) / xmaps))”.

Do you know why this happens？ Is it because of the environment configuration？

**Comment by Lzyyaa** [comment]
I try to change the 'do_interpolation = True' in test.py to 'do_interpolation = False', then the program can run normally and get the picture after style transfer.

Do you think the problem is here？ Have you ever tried to run the test.py of a single image and a single style？

**Comment by YBZh** [comment]
Thanks for your interest. Actually, I can not find the mentioned "ymaps = int(math.ceil(float(nmaps) / xmaps))" in the EFDM repository. Could you provide more information about it? for example, which file is it in?

As for the 'do_interpolation', one single style is used when do_interpolation = False, while multiple styles are considered when 'do_interpolation = True'.

**Comment by Lzyyaa** [comment]
Thanks for your reply. At first, I tried to run test.py in /ArbitraryStyleTransfer/ with a single content and a single style according to [README.md](/ArbitraryStyleTransfer#readme). At that time, line 115 of  test.py was "do_interpolation = True", and I run the file then the error occurred: ZeroDivisionError: float division by zero.

It like this:
Traceback (most recent call last):
  File "C:\Users\asus\Desktop\EFDM-main\ArbitraryStyleTransfer\test.py", line 184, in <module>
    save_image(output, str(output_name))
  File "F:\Python310\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\Python310\lib\site-packages\torchvision\utils.py", line 156, in save_image
    grid = make_grid(tensor, **kwargs)
  File "F:\Python310\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\Python310\lib\site-packages\torchvision\utils.py", line 117, in make_grid
    ymaps = int(math.ceil(float(nmaps) / xmaps))
ZeroDivisionError: float division by zero

Then I try to change the line 115 of  test.py  'do_interpolation = True' in test.py to 'do_interpolation = False', it works normally.
So, I want to know is 'do_interpolation = True'  the cause of the error? When a single content and a single style is used, do we need to change 'do_interpolation''s value?

**Comment by YBZh** [comment]
"When a single content and a single style is used, do we need to change 'do_interpolation''s value?"   -- Yes, do_interpolation should be False here. 

"ZeroDivisionError: float division by zero"  -- I guess it is a numerical problem. Please check the numerical value of "output" before applying "save_image(output, str(output_name))".

**Comment by Lzyyaa** [comment]
OK, thanks a lot.

**Comment by eleveneee** [comment]
> oat divisio

Hello, I changed the code as you said. The picture result is output, but the result of **"tensor (nan)"** is output. Do you have such a problem?

**Comment by Lzyyaa** [comment]
抱歉，我忘记输出有没有出现“tensor(nan)”了，因为当时是可以正常运行并且输出转换后的图片，所以我没有在意这个问题。不过我当时尝试的是单内容图片单风格图片的任意风格迁移，将 test.py 中的 'do_interpolation = True' 改为  'do_interpolation = False' 后可以正常运行得到风格化后的图片。否则会出现 float division by zero 的错误。
