### ISSUE TITLE
 the result of "tensor (nan)" is output

### ISSUE THREAD

**Issue by eleveneee** [YBZh/EFDM#4]
I try to change the 'do_interpolation = True' in test.py to 'do_interpolation = False', then the program can run normally and get the picture after style transfer.

Do you think the problem is here？ Have you ever tried to run the test.py of a single image and a single style？

_Originally posted by @Lzyyaa in https://github.com/YBZh/EFDM/issues/3#issuecomment-1318093910_

**Comment by eleveneee** [comment]
I changed the code as said above. The picture result is output, but the result of "tensor (nan)" is output. Do you have such a problem?

**Comment by YBZh** [comment]
1. The 'do_interpolation' should be set as False when we feed a single image and a single style to the model. 
2. The results tensor (nan) is the output of the time counting:
https://github.com/YBZh/EFDM/blob/504a4df0a8b264873ac746b84ab6b070a001ee77/ArbitraryStyleTransfer/test.py#L262
I have fixed these two problems in the current version.

**Comment by eleveneee** [comment]
> 1. The 'do_interpolation' should be set as False when we feed a single image and a single style to the model.
> 2. The results tensor (nan) is the output of the time counting:
>    https://github.com/YBZh/EFDM/blob/504a4df0a8b264873ac746b84ab6b070a001ee77/ArbitraryStyleTransfer/test.py#L262
>    
>    I have fixed these two problems in the current version.

thank you bro!
