### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ross-Hr** [YBZh/EFDM#5]
Greate work!!
How to draw Histograms of feature values in fig1 of the paper?

**Comment by hardbone6** [comment]
> Greate work!! How to draw Histograms of feature values in fig1 of the paper?

I hava the same problem

**Comment by YBZh** [comment]
You can get the figure 1 with the code in: https://github.com/YBZh/EFDM/blob/main/DomainGeneralization/imcls/vis.py
